spring:
  application:
    name: "url-shortener-service"
  jpa:
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mock
    username: mock
    hikari:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 60000
      minimum-idle: 10
      max-lifetime: 1800000
      maximum-pool-size: 100
      initialization-fail-timeout: 1
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8080
  error:
    include-message: always